# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_python2.7

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "RXnv3/0XISpaFrltG6Hd0JjBHkeJmds0hEvtcciD0QCNFOozLhk6DiJcg0vxeMLwB+u/NyDF4sDA14U1V0cmiurgyBSoRs+m4VRYa0FlOpxTGA/y8eDtPvDB8XcziGwHoL7DNADLcv5gJWnJqEBAGFdxUCEFfbHi+u5CE7z2DgACi8wJKtwm8y+dl/hj7cUgOF8EHPZzUBTsRkHF8iKy5rBbbheLPrSw3u/VytNAfJO1OkgPix3H4kryejlCDIJMd99GGSqTEaHYPDPhQPH1KKD8kU6sDqGisDq/EgEixClEs5jXQQBD4YRg6QbMALH4g9b7gNgXmQvTcremBy52YW/NiNS0sJt3SiVfUz38xaaBfHiuICbduPHAkAeIJwocbMeVQkOnyNFQl9LxvA8N2xfnJiE9QyxRTY/jVNs2su3+EwvJz4ooX3B1PLHwu2r2EyMoqYVbbQ2gRlzgr/9h+7RIIPGez/1I5WpMYSBaPMhx42CWvDfqomL9vMSZkOpyye/iHYSktyy4JpRZjtCYbowoegVaUJX9sVJ8xzCpMLYBZbbkYZ51R5RLLstvWXWvNAzIgtr/G/52PbW0jY7n7OQCZj5XogAroCvpITnXgVmVSaoPYNkXOA2gK2CIvmvogt1y2BhzEgKklJ0yT4Io/pT1N+lOgMiiEyFfiV586/g="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
