appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: RXnv3/0XISpaFrltG6Hd0JjBHkeJmds0hEvtcciD0QCNFOozLhk6DiJcg0vxeMLwB+u/NyDF4sDA14U1V0cmiurgyBSoRs+m4VRYa0FlOpxTGA/y8eDtPvDB8XcziGwHoL7DNADLcv5gJWnJqEBAGFdxUCEFfbHi+u5CE7z2DgACi8wJKtwm8y+dl/hj7cUgOF8EHPZzUBTsRkHF8iKy5rBbbheLPrSw3u/VytNAfJO1OkgPix3H4kryejlCDIJMd99GGSqTEaHYPDPhQPH1KKD8kU6sDqGisDq/EgEixClEs5jXQQBD4YRg6QbMALH4g9b7gNgXmQvTcremBy52YW/NiNS0sJt3SiVfUz38xaaBfHiuICbduPHAkAeIJwocbMeVQkOnyNFQl9LxvA8N2xfnJiE9QyxRTY/jVNs2su3+EwvJz4ooX3B1PLHwu2r2EyMoqYVbbQ2gRlzgr/9h+7RIIPGez/1I5WpMYSBaPMhx42CWvDfqomL9vMSZkOpyye/iHYSktyy4JpRZjtCYbowoegVaUJX9sVJ8xzCpMLYBZbbkYZ51R5RLLstvWXWvNAzIgtr/G/52PbW0jY7n7OQCZj5XogAroCvpITnXgVmVSaoPYNkXOA2gK2CIvmvogt1y2BhzEgKklJ0yT4Io/pT1N+lOgMiiEyFfiV586/g=}
