travis:
  secure:
    BINSTAR_TOKEN: U+hW+C17nFvbQrDXCQMhS+gvLAPbeX1s3ib1kd1/zXgw9D02eNOsirD+kNrOGg4TWyVqFhEDhxT+QO0ng0duu9dyqcUZ9rtzo3WDiGRKGENSjEomlDSD1QoQ6hwFFiaCstXsWfH10jM+gytzu+eq2B7U5ahvocSUpz80iJu9zOt93YU8WQg5dJxRMdrg8ZFXhkWICt5V9DhcX3y259HaBW18vojH6sT9/EFF2D7btO8fccOmhUOAyKLkv81GKAefLAxIKtgSj0Ei2r97QXLvdVmPw/ZsL3Ow1oC1WFaVGtwzX5d1mbOd6QodMpYyOMVbScv+NtweV8X1W15D3w7EF5Cnrkm/uAINKHrk+mX4Kozafo37LRoD7fSnwt1wS2ax6LH40L/uIwihm4qzkmVpnRQTKSzCsXvsepl/a7xdhNf9F10lsqM9lLAh33ngDgRkEGnIK2PNDNfL3FDFY0U4RkdlSxCrGL0XzqBJqj3EcSvftiAyssMnbCj0tk/5EPaKArFc8VrkZKUKBSMQq1Gp38Lto7feouabmSOidPkiLHSnxNWCYoeYAXjvMIElTKgysdJDmfQWKLu2tVFPVlmPzU2WfqG2T0ZJ+73ayYYOcm2m/t4WHkJ0wrzPoeSzP0qmx2fPY4zL4nacG7PHpKmd8qyFCLkcWKREnoHjebzveuY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
